### PR TITLE
Allow dotfiles request

### PR DESCRIPTION
**Pull request by nachoab**
I need to request dotfiles from my app. Would you consider using the allow option? is there a reason not to?

### CODE REVIEW

**Comment by nachoab** [comment]
I signed it!

**Comment by justinfagnani** [comment]
Many static file servers default to not allowing dotfiles as a security measure. It's been too common that someone includes some sensitive configuration, or the .git folder, etc. How would you feel if this were behind a flag?

**Comment by nachoab** [comment]
Polyserve is not for production but even then I agree that behind a flag is the way to go here and it works for me

**Comment by justinfagnani** [comment]
I'm going to close this for now. If you'd like to submit a PR that adds a flag I'm all for it. Thanks!

**Pull request closed without merging**
