### PR TITLE
Use published typings for pem and spdy

### PR DESCRIPTION
**Pull request by tony19**
- [ ] CHANGELOG.md has been updated

The typings for pem/spdy are now available from npm via `@types/pem` and `@types/spdy`. This patch replaces those custom typings with the published ones.

### CODE REVIEW

**Comment by justinfagnani** [comment]
I think you forgot to update package.json

**Comment by tony19** [comment]
Oops. Fixed

**Comment by FredKSchott** [comment]
LGTM, can you rebase to fix merge conflicts?

**Comment by tony19** [comment]
@FredKSchott Ok, done

**Comment by justinfagnani** [comment]
Thanks @tony19 !

**Pull request merged**
