### PR TITLE
Adds an -o option to open your default browser to an initial page

### PR DESCRIPTION
**Pull request by jeffposnick**
I find myself wanting to do open up the demo pages immediately after starting the server, so `-o demo` will automate that.

### CODE REVIEW

**Comment by ebidel** [comment]
:+1: would love this. LGTM. cc @justinfagnani for merge

**Comment by justinfagnani** [comment]
Sorry for the delay, I had notifications off somehow! Taking a look now.

**Comment by justinfagnani** [comment]
LGTM as well!

**Comment by jeffposnick** [comment]
Should be merge-able now, @justinfagnani.

**Comment by addyosmani** [comment]
LGTM3. Should be good to merge as of 08e7d20.

**Pull request merged**
