### PR TITLE
Expose packageName in the main server app

### PR DESCRIPTION
**Pull request by yangchenyun**
app.polyservePackageName is not accessible in the main server, the console.log is:
```
Files in this directory are available at localhost:8080/components/undefined/...
```

### CODE REVIEW

**Comment by yangchenyun** [comment]
Besides this bug fixes, I suggest to move all the default initialization and console.log together in the main server as well.

**Comment by yangchenyun** [comment]
Do I need to sign it if I am Google employee?

**Comment by justinfagnani** [comment]
Hi, you don't need to sign the CLA if your'e a Google employee. Can you email me to verify? I hope the bot gets fixed for this soon.

**Comment by justinfagnani** [comment]
I believe this is obsolete now

**Pull request closed without merging**
