### PR TITLE
Redirect root to target component directory

### PR DESCRIPTION
**Pull request by mbleigh**
I didn't actually run this locally, but it ought to work :)

### CODE REVIEW

**Comment by justinfagnani** [comment]
Sorry for the delay, I somehow didn't have notifications on for this repo.

I'll try this locally, but I also have another change sitting around which ads a landing page with links into files and eventually documentation. That might be a good place to hang any new features off of. WDYT?

**Comment by justinfagnani** [comment]
@robdodson FYI

**Comment by robdodson** [comment]
+1 !

**Comment by addyosmani** [comment]
Is this still an issue? (just asking as PR requires a rebase and it has been a few months).

**Comment by robdodson** [comment]
I don't think this works yet. If I go to localhost:8080 it doesn't redirect to the components/element path, it just 404s

**Comment by justinfagnani** [comment]
This patch just redirects `/components/` to `/components/{package_name}`. I'm merging this, but we should add a few more redirects like you're taking about Rob.

**Pull request merged**
