### PR TITLE
Make openPath override the component path

### PR DESCRIPTION
**Pull request by justinfagnani**

### CODE REVIEW

**Comment by azakus** [comment]
LGTM

**Comment by FredKSchott** [comment]
Uh oh, this no longer works for elements. `-o` will now open `http://localhost:8080/index.html`, which is a blank page. It used to open `http://localhost:8080/components/element-name/index.html`, which is the correct URL.

**Comment by FredKSchott** [comment]
err, wait. `-o` now does the right thing, ignore me :)

**Comment by justinfagnani** [comment]
Yeah, all this does is prefer openPath to componentUrl, rather than append.

**Comment by FredKSchott** [comment]
What's changed is that you now need the full component path, instead of just `index.html`. That'll be an unexpected change for anyone/anything currently using `open-path`, but one I can live with.

**Comment by justinfagnani** [comment]
That's true, but polyserve hasn't been prioritizing serving application projects until now, so everything was geared to serving reusable components. We need to iterate here to serve both styles.

**Comment by FredKSchott** [comment]
agreed

**Pull request merged**
